MOCKUP_TEMPLATES: list[dict] = [
    {
        "id": "home-countertop-hero",
        "name": "Kitchen Countertop Hero",
        "category": ["kitchen", "home", "appliance"],
        "scenes": ["kitchen", "home", "daily_use"],
        "platforms": ["amazon", "shopify"],
        "ratios": ["platform_default", "1_1", "4_5"],
        "composition": "center",
        "replaceableAreas": [{"id": "product", "type": "product", "x": 390, "y": 140, "width": 420, "height": 420}],
        "previewUrl": "https://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&w=900&q=80",
        "sourceUrl": "mockup://home-countertop-hero",
        "tags": ["countertop", "natural light", "clean"],
    },
    {
        "id": "office-desk-productivity",
        "name": "Office Desk Productivity",
        "category": ["electronics", "office", "home"],
        "scenes": ["office", "work", "desktop"],
        "platforms": ["amazon", "shopify"],
        "ratios": ["platform_default", "1_1", "16_9"],
        "composition": "right-product",
        "replaceableAreas": [{"id": "product", "type": "product", "x": 560, "y": 170, "width": 330, "height": 330}],
        "previewUrl": "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=900&q=80",
        "sourceUrl": "mockup://office-desk-productivity",
        "tags": ["desk", "professional", "productivity"],
    },
    {
        "id": "outdoor-camping-table",
        "name": "Outdoor Camping Table",
        "category": ["outdoor", "sports", "drinkware"],
        "scenes": ["camping", "outdoor", "travel"],
        "platforms": ["amazon", "shopify", "tiktok"],
        "ratios": ["platform_default", "4_5", "1_1"],
        "composition": "center",
        "replaceableAreas": [{"id": "product", "type": "product", "x": 420, "y": 150, "width": 360, "height": 430}],
        "previewUrl": "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=900&q=80",
        "sourceUrl": "mockup://outdoor-camping-table",
        "tags": ["camping", "wood table", "daylight"],
    },
    {
        "id": "beauty-vanity-premium",
        "name": "Beauty Vanity Premium",
        "category": ["beauty", "personal_care"],
        "scenes": ["bathroom", "vanity", "gift"],
        "platforms": ["amazon", "shopify", "tiktok"],
        "ratios": ["platform_default", "4_5", "1_1"],
        "composition": "left-product",
        "replaceableAreas": [{"id": "product", "type": "product", "x": 190, "y": 150, "width": 340, "height": 420}],
        "previewUrl": "https://images.unsplash.com/photo-1522338242992-e1a54906a8da?auto=format&fit=crop&w=900&q=80",
        "sourceUrl": "mockup://beauty-vanity-premium",
        "tags": ["vanity", "soft light", "premium"],
    },
    {
        "id": "pet-home-cozy",
        "name": "Pet Home Cozy",
        "category": ["pet", "home"],
        "scenes": ["living_room", "daily_use", "pet_care"],
        "platforms": ["amazon", "shopify"],
        "ratios": ["platform_default", "1_1", "4_5"],
        "composition": "center",
        "replaceableAreas": [{"id": "product", "type": "product", "x": 360, "y": 180, "width": 420, "height": 360}],
        "previewUrl": "https://images.unsplash.com/photo-1601758124510-52d02ddb7cbd?auto=format&fit=crop&w=900&q=80",
        "sourceUrl": "mockup://pet-home-cozy",
        "tags": ["living room", "warm", "pet"],
    },
    {
        "id": "fitness-studio-action",
        "name": "Fitness Studio Action",
        "category": ["sports", "fitness", "health"],
        "scenes": ["gym", "training", "daily_use"],
        "platforms": ["amazon", "shopify", "tiktok"],
        "ratios": ["platform_default", "4_5", "1_1"],
        "composition": "center",
        "replaceableAreas": [{"id": "product", "type": "product", "x": 400, "y": 180, "width": 380, "height": 380}],
        "previewUrl": "https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=900&q=80",
        "sourceUrl": "mockup://fitness-studio-action",
        "tags": ["gym", "training", "clean"],
    },
]
